# config/config.yaml
server:
  port: 8080

storage:
  type: sqlite
  path: /config/data.db

endpoints:
  - name: Google
    url: https://www.google.com
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: GitHub
    url: https://www.github.com
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: Delfi
    url: https://www.delfi.ee
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: http://localhost:3001/dashboard
    url: http://localhost:3001/dashboard
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500ms"
      - "[CONTENT_TYPE] == 'text/html'"   
  - name: http://localhost:3001/api/health
    url: http://localhost:3001/api/health
    interval: 10s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500ms"
      - "[CONTENT_TYPE] == 'application/json'"