name: Infra (Terraform)
on:
push:
paths:
- 'terraform/**'
workflow_dispatch:


jobs:
terraform:
runs-on: ubuntu-latest
defaults:
run:
working-directory: terraform
steps:
- uses: actions/checkout@v4


- name: Setup Terraform
uses: hashicorp/setup-terraform@v3
with:
terraform_wrapper: false


- name: Configure AWS creds
uses: aws-actions/configure-aws-credentials@v4
with:
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
aws-region: ${{ secrets.AWS_REGION }}


- name: Terraform Init
run: terraform init


- name: Terraform Validate
run: terraform validate


- name: Terraform Plan
run: terraform plan -input=false -out=tfplan


- name: Terraform Apply (auto-approve)
if: github.ref == 'refs/heads/main'
run: terraform apply -input=false -auto-approve tfplan


- name: Export Public IP
id: tfout
run: echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT


- name: Save IP artifact
uses: actions/upload-artifact@v4
with:
name: ec2-ip
path: |
terraform/terraform.tfstate
retention-days: 7