name: Deploy to Hetzner

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kodą
        uses: actions/checkout@v4

      - name: Įdiegti Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Deploy su Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml \
            --private-key <(echo "${{ secrets.HETZNER_SSH_KEY }}") \
            -u root