---
- name: Add Docker GPG key
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg


- name: Add Docker repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable


- name: Install Docker packages
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present


- name: Add user to docker group
  user:
    name: "{{ app_user }}"
    groups: docker
    append: yes


- name: Create app dir
  file:
  path: "{{ app_dir }}"
  state: directory
  owner: "{{ app_user }}"
  group: "{{ app_user }}"
  mode: "0755"


- name: Place docker-compose.yml
  copy:
    src: "../../deploy/docker-compose.yml"
    dest: "{{ compose_file }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"