apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx:latest
      volumeMounts:
        - name: my-persistent-storage
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: my-persistent-storage
      persistentVolumeClaim:
        claimName: mypvc