apiVersion: v1
kind: Pod
metadata:
  name: web-application
spec:
  containers:
    - name: web-app
      image: nginx
      envFrom:
        - configMapRef:
            name: app-config
            key: env