name: Build, Push and Test Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/minimal-linux-app:latest

  test-container:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Pull image from DockerHub
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/minimal-linux-app:latest

    - name: Run container and test output
      run: |
        output=$(docker run --rm ${{ secrets.DOCKER_USERNAME }}/minimal-linux-app:latest)
        echo "Program output: $output"
        if [ "$output" != "Hello from minimal Linux (Alpine)!" ]; then
          echo "Test failed: Output does not match expected"
          exit 1
        fi
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/minimal-linux-app:latest

    - name: Show Docker image size
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/minimal-linux-app:latest
        docker image inspect ${{ secrets.DOCKER_USERNAME }}/minimal-linux-app:latest --format='Image size: {{.Size}} bytes'